# Generated by Django 3.2.20 on 2023-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200, unique=True)),
                ('lastPrice', models.FloatField()),
                ('priceChangePercent', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('quoteVolume', models.FloatField()),
                ('inGreen', models.IntegerField(default=0)),
            ],
        ),
    ]
